DATA:
  DATASET: imagenet22K
  IMG_SIZE: 192
MODEL:
  TYPE: swinv2
  NAME: test
  DROP_PATH_RATE: 0.2
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12   #12
TRAIN:
  EPOCHS: 20 #90
  WARMUP_EPOCHS: 2  #5
  WEIGHT_DECAY: 0.1
  BASE_LR: 1.25e-3 # 4
  WARMUP_LR: 1.25e-6 #7
  MIN_LR: 1.25e-6